### ISSUE TITLE
Monitor Superset Performance

### ISSUE THREAD

**Issue by som2014** [apache/incubator-superset#10659]
I don't find any articles or docs describing how we can monitor superset in production environment. So any help regarding how we can have matrix which we can use to monitor superset ?

**Comment by hemajv** [comment]
Yes, we have deployed Superset in a production environment and as we have more users, it is becoming critical to monitor. Is there any future plan for exposing Prometheus metrics for Superset?

**Comment by bkyryliuk** [comment]
Superset uses statsd: https://github.com/statsd/statsd
You can find a number of metrics already there.

If you run it using gunicorn: https://docs.gunicorn.org/en/stable/instrumentation.html

As for machine / DB utilization: cpu, memory, disk, network  - that depends on how you run it, e.g. in AWS you'll have cloudwatch metrics.

Celery needs a bit of magic:
* https://docs.celeryproject.org/en/stable/userguide/monitoring.html
* https://medium.com/meilleursagents-engineering/how-we-monitor-asynchronous-tasks-da25728173d6

**Comment by som2014** [comment]
@bkyryliuk  I have used the following command in my superset_config file
```from superset.stats_logger import StatsdStatsLogger
STATS_LOGGER = StatsdStatsLogger(host='0.0.0.0', port=8125, prefix='superset')
```

Then i am using gunicorn 
```
 nohup  gunicorn \
      -w 6 \
      -k gevent \
      --timeout 120 \
      -b  0.0.0.0:8088 \
      --limit-request-line 0 \
      --limit-request-field_size 0 \
      --statsd-host 0.0.0.0:8125 \
      "superset.app:create_app()" &
```

AT   `<IP ADDRESS>:8125 `i am not seeing any metrics i am doing anything wrong here ?

**Comment by som2014** [comment]
@bkyryliuk  I am getting this error
```
gunicorn/instrument/statsd.py", line 127, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by som2014** [comment]
Thanks @bkyryliuk

**Comment by Julien-Fruteau** [comment]
> [@bkyryliuk](https://github.com/bkyryliuk) I have used the following command in my superset_config file
> 
> ```
> STATS_LOGGER = StatsdStatsLogger(host='0.0.0.0', port=8125, prefix='superset')
> ```
> 
> Then i am using gunicorn
> 
> ```
>  nohup  gunicorn \
>       -w 6 \
>       -k gevent \
>       --timeout 120 \
>       -b  0.0.0.0:8088 \
>       --limit-request-line 0 \
>       --limit-request-field_size 0 \
>       --statsd-host 0.0.0.0:8125 \
>       "superset.app:create_app()" &
> ```
> 
> AT `<IP ADDRESS>:8125 `i am not seeing any metrics i am doing anything wrong here ?

Hello @Asturias-sam, and for anyone ending up there,

from my understanding you missed configuring a StatsD server listening to metrics sent by gunicorn (which is running superset on port 8088 and sending statsd metrics to `<ip-addr>:8125` as per the command provided)

⚠️ superset is just using a statsd client, it does not run a statsd server

For example, using the `docker-compose-non-dev.yml`, a statsd-exporter service can be added to listen for metrics : 

````yaml
  # ....
  superset:
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    build:
      <<: *common-build
    container_name: superset_app
    # 📢 using statsd-host `statsd_exporter:9125`
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn", "--statsd-host statsd_exporter:9125", "--statsd-prefix superset"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
  # ....

  # 📢 new service:
  statsd-exporter:
    container_name: statsd_exporter
    image: prom/statsd-exporter
    ports:
      - 9125:9125/udp #ℹ️ listens for incoming statsd metrics
      - 9102:9102     #ℹ️ exposes prometheus metrics on :9102/metrics with superset prefix
````

ℹ️ the target here is for a prometheus server to scrap metrics from this statsd-exporter (on port 9102)
💡 from statsd github repo, a "bare" server can probably used with the [Dockerfile](https://github.com/statsd/statsd/blob/master/Dockerfile) they provide
 ⚠️this example cannot be run as is since the `docker-bootstrap.sh app-gunicorn` command does not natively allow additional parameters (it needs modification beyond this topic)
