### ISSUE TITLE
can not access superset 0.36.0 ui 

### ISSUE THREAD

**Issue by 4ss3g4f** [apache/incubator-superset#9590]
can not access superset 0.36.0 ui  port 8088

### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/22811935/79711378-d9248580-82f1-11ea-9f51-e8cae4aeb542.png)

![image](https://user-images.githubusercontent.com/22811935/79711466-0cffab00-82f2-11ea-93cc-eb63f13a66f5.png)

#### How to reproduce the bug

1. docker stack deploy -c superset.yaml superset
2. See error below

### Environment

(please complete the following information):

- superset version: `0.36.0`
- python version: `3.6.10`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X ] I have reproduced the issue with at least the latest released version of superset.
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

```
version: '3.7'

networks:
  bridge:
    external: true
    
services:
  superset:
    image: amancevice/superset:0.36.0
    networks:
      - bridge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kubernetes.mncplaymedia.com:8080/healthz"]
      interval: 1s
      timeout: 3s
      retries: 60
    deploy:
      restart_policy:                                                   
        condition: on-failure                                           
        delay: 5s                                                       
        max_attempts: 3                                                 
        window: 120s
    depends_on:
      - "acid-test-cluster.default.svc.cluster.local"
      - "keydb.keydb.svc.cluster.local"
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - /home/core/superset/superset_config.py:/etc/superset/superset_config.py
```

```
import os

MAPBOX_API_KEY = os.getenv('MAPBOX_API_KEY', '')
CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_DEFAULT_TIMEOUT': 86400,
    'CACHE_KEY_PREFIX': 'superset_',
    'CACHE_REDIS_HOST': 'keydb.keydb.svc.cluster.local',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 1,
    'CACHE_REDIS_URL': 'redis://keydb.keydb.svc.cluster.local:6379/1'}
SQLALCHEMY_DATABASE_URI = \
    'postgresql+psycopg2://postgres:password@acid-test-cluster.default.svc.cluster.local:5432/superset_swarm'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = 'admin'
```

Actions

> [2020-04-20 03:14:05 +0000] [1] [INFO] Starting gunicorn 20.0.4
> 
> 
> [2020-04-20 03:14:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
> 
> 
> [2020-04-20 03:14:05 +0000] [1] [INFO] Using worker: threads
> 
> 
> [2020-04-20 03:14:05 +0000] [10] [INFO] Booting worker with pid: 10
> 
> 
> [2020-04-20 03:14:06 +0000] [19] [INFO] Booting worker with pid: 19
> 
> 
> [2020-04-20 03:14:06 +0000] [20] [INFO] Booting worker with pid: 20
> 
> 
> /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
> 
> 
>   """)
> 
> 
> [2020-04-20 03:14:37 +0000] [10] [ERROR] Error handling request /
> 
> 
> Traceback (most recent call last):
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 271, in handle
> 
> 
>     keepalive = self.handle_request(req, conn)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
> 
> 
>     respiter = self.wsgi(environ, resp.start_response)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 376, in <lambda>
> 
> 
>     __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 307, in _get_current_object
> 
> 
>     return self.__local()
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/flask/globals.py", line 52, in _find_app
> 
> 
>     raise RuntimeError(_app_ctx_err_msg)
> 
> 
> RuntimeError: Working outside of application context.
> 
> 
> 
> This typically means that you attempted to use functionality that needed
> 
> 
> to interface with the current application object in some way. To solve
> 
> 
> this, set up an application context with app.app_context().  See the
> 
> 
> documentation for more information.
> 
> 
> [2020-04-20 03:14:42 +0000] [10] [ERROR] Error handling request /
> 
> 
> Traceback (most recent call last):
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 271, in handle
> 
> 
>     keepalive = self.handle_request(req, conn)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
> 
> 
>     respiter = self.wsgi(environ, resp.start_response)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 376, in <lambda>
> 
> 
>     __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 307, in _get_current_object
> 
> 
>     return self.__local()
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/flask/globals.py", line 52, in _find_app
> 
> 
>     raise RuntimeError(_app_ctx_err_msg)
> 
> 
> RuntimeError: Working outside of application context.
> 
> 
> 
> This typically means that you attempted to use functionality that needed
> 
> 
> to interface with the current application object in some way. To solve
> 
> 
> this, set up an application context with app.app_context().  See the
> 
> 
> documentation for more information.
> 
> 
> /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
> 
> 
>   """)
> 
> 
> [2020-04-20 03:14:43 +0000] [19] [ERROR] Error handling request /
> 
> 
> Traceback (most recent call last):
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 271, in handle
> 
> 
>     keepalive = self.handle_request(req, conn)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
> 
> 
>     respiter = self.wsgi(environ, resp.start_response)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 376, in <lambda>
> 
> 
>     __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 307, in _get_current_object
> 
> 
>     return self.__local()
> 
> 
>   File "/usr/local/lib/python3.6/site-packages/flask/globals.py", line 52, in _find_app
> 
> 
>     raise RuntimeError(_app_ctx_err_msg)
> 
> 
> RuntimeError: Working outside of application context.
> 
> 
> 
> This typically means that you attempted to use functionality that needed
> 
> 
> to interface with the current application object in some way. To solve
> 
> 
> this, set up an application context with app.app_context().  See the
> 
> 
> documentation for more information.
