### ISSUE TITLE
Problems with mapbox

### ISSUE THREAD

**Issue by aspedrosa** [apache/incubator-superset#9718]
I wanted to check if it was all ok with the Mapbox chart so I created a simple query on SQL Lab
```
SELECT to_date('20170103','YYYYMMDD') as ddtm, CAST(38.7377 as float) as lat, CAST(-9.1722 as float) as lon
UNION
SELECT to_date('20170103','YYYYMMDD') as ddtm, CAST(40.6419 as float), CAST(-8.6519 as float)
```
Ran the query, clicked "Explore" to move to the new chart view. Filled the necessary fields and then clicked "Run Query" and then the entire tab froze.

### Expected results

The Mapbox is displayed

### Actual results

The entire tab freezes 

#### Screenshots

The errors that were logged after filling the required values of the chart controls and then clicking on the "Run Query" button.

![Screenshot_20200502_143354](https://user-images.githubusercontent.com/23409890/80869867-b2276580-8c9a-11ea-81a7-96fdf39eac71.png)
![Screenshot_20200502_143409](https://user-images.githubusercontent.com/23409890/80869869-b5225600-8c9a-11ea-9a66-9d284fff1a2d.png)

Also a lot of "componentWillMount has been renamed ..." warnings were logged.

#### How to reproduce the bug

1. Create a datasource/query that contains latitude, longitude and datetime values
2. Create a new MapBox chart
3. Fill the"longitude" and "latitude" fields under the query section
4. Press "Run Query"

### Environment

Running on docker
- superset version: 0.36.0
- python version: 3.6.9
- node.js version: 10.20.1
- npm version: 6.14.4

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
Below is my docker setup.
```
.
|-- docker
|   `-- superset
|       |-- Dockerfile
|       |-- docker-init.sh (copy of the original docker-init.sh)
|       `-- pythonpath_docker
|           `-- superset_config_docker.py (currently only has PUBLIC_ROLE_LIKE_GAMMA = True)
`-- superset (clone of the superset repo on tag 0.36)
```
The Dockerfile that I'm using was based on the original provided on the repository root. The only changes that I made was to:
- install the requirements-extra.txt on the superset-py target
- remove the dev target

Section of the docker-compose.yml related to superset:

```
x-superset-app-build: &superset-app-build
  context: ../superset
  dockerfile: ../docker/superset/Dockerfile
  target: lean
x-superset-depends-on: &superset-depends-on
  - postgres
  - redis
x-superset-volumes: &superset-volumes
  - ../superset/docker/docker-init.sh:/app/docker-init.sh
  - ./superset/pythonpath_docker:/app/pythonpath_docker
  - superset_home:/app/superset_home
x-superset-environment: &superset-environment
  DATABASE_DIALECT: postgresql
  DATABASE_HOST: postgres
  DATABASE_PORT: 5432
  DATABASE_USER: ${POSTGRES_SUPERSET_USER}
  DATABASE_PASSWORD: ${POSTGRES_SUPERSET_PASSWORD}
  DATABASE_DB: ${POSTGRES_SUPERSET_DB}
  REDIS_HOST: redis
  REDIS_PORT: 6379
  SUPERSET_ENV: production
  MAPBOX_API_KEY: ${SUPERSET_MAPBOX_API_KEY}
  PYTHONPATH: /app/pythonpath:/app/pythonpath_docker

version: "3.7"
services:
  superset:
    build: *superset-app-build
    restart: unless-stopped
    environment: *superset-environment
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    ports:
      - 8088:8080
    networks:
      - all

  superset-init:
    build: *superset-app-build
    command: ["/app/docker-init.sh"]
    environment: *superset-environment
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    networks:
      - all

  superset-worker:
    build: *superset-app-build
    command: ["celery", "worker", "--app=superset.tasks.celery_app:app", "-Ofair"]
    restart: unless-stopped
    environment: *superset-environment
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    networks:
      - all

```
